import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
// Monaco's own Monarch compiler and lexer, imported by relative path for the same
// reason monaco-setup.ts does (Vite can't resolve deep monaco-editor specifiers).
import { compile } from '../../../node_modules/monaco-editor/esm/vs/editor/standalone/common/monarch/monarchCompile.js';
import { MonarchTokenizer } from '../../../node_modules/monaco-editor/esm/vs/editor/standalone/common/monarch/monarchLexer.js';
import { qplWasmPath } from '../../data/qpl/testUtils';

/**
 * The qpl grammar is generated by the wasm (qplLangConfig) and handed to Monaco,
 * which is very forgiving: a grammar whose keyword cases can't match still
 * "works" - everything just comes out as an identifier. So this runs the real
 * grammar through Monaco's real compiler and lexer and checks the tokens.
 * (Regression: `@default` was serialised mid-`cases`, hiding every keyword.)
 */
describe.skipIf(!qplWasmPath)('qpl syntax highlighting', () => {
    const tokenize = async (line: string) => {
        const qpl = await import('qpl');
        try {
            qpl.initSync({ module: readFileSync(qplWasmPath!) });
        } catch {
            /* already initialised by an earlier test in this process */
        }
        const lexer = compile('qpl', qpl.qplLangConfig().monarch);
        const tokenizer = new MonarchTokenizer(
            { languageIdCodec: { encodeLanguageId: () => 1 } },
            { getColorTheme: () => ({ tokenTheme: {} }) },
            'qpl',
            lexer,
            { getValue: () => 20000, onDidChangeConfiguration: () => ({ dispose() {} }) },
        );
        const { tokens } = tokenizer.tokenize(line, true, tokenizer.getInitialState());
        return tokens
            .map((t: { offset: number; type: string }, i: number) => [line.slice(t.offset, tokens[i + 1]?.offset).trim(), t.type.replace(/\.qpl$/, '')])
            .filter(([text]: string[]) => text !== '');
    };
    const kind = (toks: string[][], text: string) => toks.find(([t]) => t === text)?.[1];

    it('highlights statement keywords, aggregates and comments', async () => {
        const t = await tokenize('select avg price by sym from trades where size > 100 order price desc / top');
        for (const kw of ['select', 'by', 'from', 'where', 'order', 'desc']) expect(kind(t, kw), kw).toBe('keyword');
        expect(kind(t, 'avg')).toBe('predefined');
        expect(kind(t, '100')).toBe('number');
        expect(kind(t, 'trades')).toBe('identifier');
        expect(t.at(-1)![1]).toBe('comment');
    });

    it('highlights joins, builtins and word operators', async () => {
        const t = await tokenize('select from trades `sym lj quotes `sym where sym like "A*"');
        expect(kind(t, 'lj')).toBe('operator');
        expect(kind(t, 'like')).toBe('operator');
        expect(kind(t, '`sym')).toBe('type');
        expect(kind(await tokenize('t: collect lazy select from x'), 'collect')).toBe('keyword');
    });

    it('highlights strings and numeric literals', async () => {
        const t = await tokenize('x: 1.5 + 2 * 0101b, "hi"');
        expect(kind(t, '1.5')).toBe('number.float');
        expect(kind(t, '2')).toBe('number');
        expect(kind(t, '0101b')).toBe('number');
        expect(t.some(([, type]: string[]) => type.startsWith('string'))).toBe(true);
    });
});
