cabal-version:      3.0
name:               fastboard-server
version:            0.1.0.0
synopsis:           Serves the built FastBoard app and a Reddit search SSE stream
license:            MIT
build-type:         Simple

executable fastboard-server
    main-is:          Main.hs
    default-language: Haskell2010
    ghc-options:      -Wall -threaded
    build-depends:    base >=4 && <5, aeson, bytestring, filepath, http-conduit, http-types, scotty, text, time,
                      wai-middleware-static, warp
